### ISSUE TITLE
Can't run LSP in Repl.it

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [OmniSharp/omnisharp-roslyn#2344]
Here is my [`.replit`](https://replit.com/@EmilySeville7cfg/Cant-run-C-language-server) config (consider just [`languages.csharp`](https://docs.replit.com/programming-ide/configuring-repl) section):

```toml
run = "dotnet run"
entrypoint = "main.cs"

hidden = ["bin", "obj"]

[env]
DOTNET_NOLOGO = "1"
DOTNET_CLI_TELEMETRY_OPTOUT = "1"

[packager]
language = "dotnet"

[packager.features]
packageSearch = true

[nix]
channel = "stable-21_11"

[languages.csharp]
pattern = "**/*.cs"
languageServer = { "start" = "omnisharp" }
```

When I press `Ctrl+Space` in `.cs` files no intellisense is shown. How to fix this problem?
