### ISSUE TITLE
Server fails to start with "OmniSharp requires the .NET 6 SDK or higher be installed." on .NET 6, 7

### ISSUE THREAD

**Issue by dkaszews** [OmniSharp/omnisharp-roslyn#2423]
Trying to get vim-OmniSharp to work, but the server fails to start, complaining about not finding SDK, despite using the exact one from link in next message. Also an issue with .NET7, both using `DOTNET_ROOT` or installing in `/usr/share/dotnet`, despite using both to successfully compile projects. Reproduces on all versions from latest v1.39.1 to v1.38.0 which is oldest supporting .NET6.

OS is Ubuntu 22.04 LTS aarch64 on Raspberry Pi 4 Model B Rev 1.2

Previously opened in [vim-OmniSharp](https://github.com/OmniSharp/omnisharp-vim/issues/799), moved here because also fails when run outside vim.

```shell
> /home/dkaszews/Downloads/omnisharp-linux-arm64-net6.0/OmniSharp                         
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Host","Message":"Starting OmniSharp on Unknown 0.0 (Unknown)"},"Seq":1,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK"},"Seq":2,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"DotNetPath set to /home/dkaszews/Downloads/dotnet-sdk-6.0.302-linux-arm64/dotnet"},"Seq":3,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"ERROR","Name":"OmniSharp.MSBuild.Discovery.Providers.SdkInstanceProvider","Message":"OmniSharp requires the .NET 6 SDK or higher be installed. Please visit https://dotnet.microsoft.com/download/dotnet/6.0 to download the .NET SDK."},"Seq":4,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.Discovery.MSBuildLocator","Message":"Located 0 MSBuild instance(s)"},"Seq":5,"Type":"event"}
Could not locate MSBuild instance to register with OmniSharp.
dkaszews@Cuddles-Berry:~/code/PowerShell [dkaszews-update-help-implicit-culture +4 ~0 -0 !]


> & "$env:DOTNET_ROOT/dotnet" --info                                                      

global.json file:
  /home/dkaszews/code/PowerShell/global.json

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/home/dkaszews/Downloads/dotnet-sdk-6.0.302-linux-arm64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/home/dkaszews/Downloads/dotnet-sdk-6.0.302-linux-arm64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/home/dkaszews/Downloads/dotnet-sdk-6.0.302-linux-arm64/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by dkaszews** [comment]
I compiled from source, set `$DOTNET_ROOT` to the `.dotnet` in repo, works. Try with `OmniSharp` downloaded from releases, works. Move `.dotnet` to another directory, does not work. Move it back, works. Move it again to another directory, does not work. Move it again back to repo, no longer works.

So something is seriously wrong.

**Comment by filipw** [comment]
The SDK provider requires `dotnet` command to be available on your path, it literally [runs the process](https://github.com/microsoft/MSBuildLocator/blob/f1cf5647d1a13f55ff0beff455617fe75280456f/src/MSBuildLocator/DotNetSdkLocationHelper.cs#L80-L97) and then checks for the output. Do you have it there?

**Comment by dkaszews** [comment]
I managed to solve it by setting `$DOTNET_ROOT` to .NET6 **and** adding it to `$PATH`. If I don't add to `$PATH`, then I get the error as above. If I don't add to `$DOTNET_ROOT`, then I get an error about missing `libhostfxr.so`.

Also, I got same error about missing SDK if I used .NET7, it only got resolved by copying the `SDK` folder from .NET6. Maybe the `SdkInstanceProvider` does not like the `-preview` suffix?

```
  6.0.302 [/home/dkaszews/.dotnet/sdk]
  7.0.100-preview.6.22352.1 [/home/dkaszews/.dotnet/sdk]
```

Also, why does `SdkInstanceProvider` does not use `$DOTNET_ROOT`? It is confusing that one part of `OmniSharp` tells me that I need to set it, then another silently failes because it cannot find `dotnet`. If anything, it should provide better error message depeding on whether it cannot find the SDK it likes, or it cannot find `dotnet` at all.

**Comment by filipw** [comment]
By default prereleases are not included, they can be included by setting the following option in `omnisharp.json` https://github.com/OmniSharp/omnisharp-roslyn/blob/04a561ca69584ab0bad1fd3fa75a14006e9afd7d/omnisharp.json#L13-L15

The `SdkInstanceProvider` yields the search to `Microsoft.Build.Locator` which is the one that runs and discovers dotnet from the PATH. We can only improve our error message to make it more obvious.

**Comment by dkaszews** [comment]
Yeah, would be good to distinguish the following cases:
* cannot find dotnet in `$PATH`
* can find dotnet, but no 6+ SDKs
* can find dotnet, but all SDKs preview

Adding a verbose log which lists all SDKs, then comments which are ignored and why should be good.

If you can point me to the right file, I'll take a look what I can do.

**Comment by litoj** [comment]
In my case it doesn't work even with just normal builds:
```sh
$ which dotnet

/usr/bin/dotnet
```

```yaml
$ dotnet --info

.NET SDK:
 Version:           9.0.112
 Commit:            191254d648
 Workload version:  9.0.100-manifests.b3871ecb
 MSBuild version:   17.12.50+191254d64

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.112/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      10.0.0
  Architecture: x64
  Commit:       b0f34d51fc

.NET SDKs installed:
  9.0.112 [/usr/share/dotnet/sdk]
  10.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /home/kepis/Documents/school/PG/SP/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

```json
$ omnisharp

{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Host","Message":"Starting OmniSharp on Unknown 0.0 (Unknown)"},"Seq":1,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK"},"Seq":2,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"Using the 'dotnet' on the PATH."},"Seq":3,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Services.DotNetCliService","Message":"DotNetPath set to dotnet"},"Seq":4,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"ERROR","Name":"OmniSharp.MSBuild.Discovery.Providers.SdkInstanceProvider","Message":"OmniSharp requires the .NET 6 SDK or higher be installed. Please visit https://dotnet.microsoft.com/download/dotnet/6.0 to download the .NET SDK."},"Seq":5,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.Discovery.MSBuildLocator","Message":"Located 0 MSBuild instance(s)"},"Seq":6,"Type":"event"}
Could not locate MSBuild instance to register with OmniSharp.
```

When I install specifically dotnet-6, then it does work, except it only starts and then says I cannot use it for the project, because the project requires dotnet 9, as I've set in the `global.json`
